name: Development Build (Galaxy A50)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'

jobs:
  oneui-kus-e:
    name: Build KernelSU One UI 4 (Enforcing)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Kolkata"
        timezoneMacos: "Asia/Kolkata"
        timezoneWindows: "Indian Standard Time"
        
    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update
      
    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y
    
    - name: Setup KernelSU
      run: |
          set -eo pipefail
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          cd KernelSU
          echo "KSU_VERSION=$(($(git rev-list --count HEAD) + 10200))" >> $GITHUB_ENV
          cd -
    
    - name: Send build message to Telegram
      uses: appleboy/telegram-action@master
      env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: Automated Build Started for KernelSU ${{ env.KSU_VERSION }} !

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Build KernelSU 
      run: |
          set -eo pipefail
          echo "  I: Building Mint kernel ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          ./build.sh --automated --device a50 --variant oneui --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname KernelSU-*.zip` ./release/

    - name: Upload build to Telegram
      uses: appleboy/telegram-action@master
      env: 
          TELEGRAM_TO: "${{ secrets.TELEGRAM_TO }}"
          TELEGRAM_TOKEN: "${{ secrets.TELEGRAM_TOKEN }}"
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
         KernelSU ${{ env.KSU_VERSION }}
         Get latest manager app
         at https://t.me/KernelSU_group/3234
         
        document: ./release/*.zip
