name: KernelSU for (Galaxy A50)

on:
  push:
    branches: ["ksu"]
  workflow_dispatch:

jobs:
  oneui-s-n:
    name: Build One UI 4 (KSU)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"
        submodules: true

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq curl -y

    - name: Build KernelSU
      run: |
          set -eo pipefail
          echo "  I: Building KernelSU ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          ./build.sh --automated --device a50 --variant oneui --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname KernelSU-*.zip` ./release/

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50_oneui-s-n.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Configs
        path: 'release/kernel_config_a50_oneui-s-n.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release'
        if-no-files-found: error

  aosp-s-n:
    name: Build AOSP 12 (KSU)
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"
        submodules: true

    - name: Export build branch
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: branch_name

    - name: Update Debian/Ubuntu Repositories
      run: sudo apt-get update

    - name: Install Debian/Ubuntu dependencies
      run: sudo apt-get install bzip2 lib32stdc++6 libc6-dev-i386 libncurses5 jq -y

    - name: Build KernelSU
      run: |
          set -eo pipefail
          echo "  I: Building KernelSU ${GITHUB_REF##*/}-${GITHUB_RUN_NUMBER}"
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          ./build.sh --automated --device a50 --variant aosp --android 12

    - name: Prepare release package
      run: |
          mkdir -p ./release
          mv -f `find ./ -iname KernelSU-*.zip` ./release/

    - name: Prepare build config artifact
      run: |
          cp .config ./release/kernel_config_a50_aosp-s-n.txt

    - name: Upload build config artifact
      uses: actions/upload-artifact@v2
      with:
        name: Kernel Configs
        path: 'release/kernel_config_a50_aosp-s-n.txt'
        if-no-files-found: error

    - name: Upload release package
      uses: actions/upload-artifact@v2
      with:
        name: Release
        path: 'release'
        if-no-files-found: error

  release:
    name: Release files and configs
    if: ${{ !contains(github.event.head_commit.message, '[skip rel]') }}
    needs: [oneui-s-n,aosp-s-n]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v2

    - uses: szenius/set-timezone@v1.0
      with:
        timezoneLinux: "Asia/Manila"
        timezoneMacos: "Asia/Manila"
        timezoneWindows: "Philippine Standard Time"

    - name: Merge Releases
      uses: actions/download-artifact@v2
      with:
        name: Release
        path: release

    - name: Delete build config files
      run: |
          set -eo pipefail
          rm -rf ./release/kernel_config_*.txt

    - name: Upload release
      uses: Hs1r1us/Release-AIO@v1.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # The name of the tag
        tag_name: mainline-${{ github.run_number }}_a50dx
        prerelease: true
        release_name: KernelSU for A50
        asset_files: './release'
